services:
  core-fe:
    container_name: core-fe
#    image:  goafabric/core-service-native${_Values_server_arch}:1.0.1
    image:  goafabric/core-fe:1.0.3-SNAPSHOT
    restart: 'no'
    ports:
      - "50400:50400"
    command: "-Xmx32m"

    healthcheck:
      test: "curl -f http://localhost:50400/actuator/health || exit 1"
      disable: true #disabled for native images because of no curl
      interval: 5s
      timeout: 10s
      retries: 5

    volumes:
      - tmp_catalog:/tmp
      - applogs_catalog:/usr/share/logs
    networks:
      - ${_Values_root_name}-net
    environment:
      #application
      TZ: Europe/Berlin
      server.port: "50400"
      server.tomcat.threads.max: "20"
      server.forward-headers-strategy: FRAMEWORK

      #security
      security.authentication.enabled: "false"

      #monitoring
      management.endpoint.health.show-details: always
      management.endpoints.web.exposure.include: "health,heapdump,circuitbreakers,prometheus"

      #forntend
      frontend.core-service.uri: "http://core-service:50400"
      frontend.catalog-service.uri: "http://catalog-service:50600"

      monitoring.view.tracing.url: "http://localhost:16686/search"
      monitoring.view.loki.url: "http://localhost:3000/explore"
      monitoring.view.s3.url: "http://localhost:9101/browser/objects"

      #log levels
      logging.level.root: "WARN"
      logging.level.org.goafabric: "INFO"
      logging.level.org.springframework: "INFO"

    depends_on:
      postgres:
        condition: service_healthy