services:
  auth-server:
    container_name: auth-server
    image: goafabric/spring-auth-server-native${_Values_server_arch}:1.0.2
    restart: 'no'
    ports:
      - "30200:30200"
    command: [ "-Xmx32m" ]
    environment:
      #application
      server.forward-headers-strategy: FRAMEWORK

      #auth
      spring.security.authorization.base-uri: "/oidc"
      spring.security.authorization.clients: "oauth2-proxy:none"
      spring.security.authorization.users: "user1:user1,user2:user2,user3:user3,user4:user4"
    networks:
      - ${_Values_root_name}-net
