#application
server:
  port: 50400
  tomcat.threads.max: 20
  forward-headers-strategy: FRAMEWORK

#monitoring
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,prometheus,heapdump"

#tracing
spring.application.name: core-service
management.tracing.sampling.probability: "1.0"
logging.level.io.opentelemetry: "OFF"
management.otlp.tracing.endpoint: "http://localhost:4318/v1/traces"

#oidc
security.authentication.enabled: false

spring:
  security:
    oauth2:
      base-uri: "http://127.0.0.1:30200/oidc"
      authorization-uri: "http://127.0.0.1:30200/oidc/auth"
#      base-uri: http://localhost:8080/oidc/realms/tenant-{tenantId}/protocol/openid-connect
#      authorization-uri: http://localhost:8080/oidc/realms/tenant-{tenantId}/protocol/openid-connect/auth
#      logout-uri: http://localhost:8080/oidc/realms/tenant-{tenantId}/protocol/openid-connect/logout
  
      client-id: "oauth2-proxy"
      client-secret: "none"
      user-name-attribute: "preferred_username"

#logging
logging.pattern.level: "%5p tenantId=%X{tenantId:-}" #"%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] tenantId=%X{tenantId:-}"

logging.level.root: "WARN"
logging.level.org.springframework: "INFO"

logging.level.org.goafabric: "INFO"
logging.level.org.flywaydb.core: "INFO"
logging.level.org.hibernate.SQL: "INFO"

#vaadin
spring.mustache.check-template-location: false
vaadin.whitelisted-packages: com.vaadin,org.vaadin,dev.hilla
vaadin.url-mapping: "/frontend/*"

frontend.catalog-service.uri: "http://localhost:50600"
frontend.core-service.uri: "http://localhost:50800"

monitoring.view.tracing.url: "http://localhost:16686/search"
monitoring.view.loki.url: "http://localhost:3000/explore"
monitoring.view.s3.url: "http://localhost:9101/browser/objects"